# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mrshark45/data/Workspace/Master/Anul1/IPG/gfx-framework-ipg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mrshark45/data/Workspace/Master/Anul1/IPG/gfx-framework-ipg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mrshark45/data/Workspace/Master/Anul1/IPG/gfx-framework-ipg/CMakeFiles /home/mrshark45/data/Workspace/Master/Anul1/IPG/gfx-framework-ipg//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mrshark45/data/Workspace/Master/Anul1/IPG/gfx-framework-ipg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GFXFramework

# Build rule for target.
GFXFramework: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GFXFramework
.PHONY : GFXFramework

# fast build rule for target.
GFXFramework/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/build
.PHONY : GFXFramework/fast

src/components/camera_input.o: src/components/camera_input.cpp.o
.PHONY : src/components/camera_input.o

# target to build an object file
src/components/camera_input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/camera_input.cpp.o
.PHONY : src/components/camera_input.cpp.o

src/components/camera_input.i: src/components/camera_input.cpp.i
.PHONY : src/components/camera_input.i

# target to preprocess a source file
src/components/camera_input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/camera_input.cpp.i
.PHONY : src/components/camera_input.cpp.i

src/components/camera_input.s: src/components/camera_input.cpp.s
.PHONY : src/components/camera_input.s

# target to generate assembly for a file
src/components/camera_input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/camera_input.cpp.s
.PHONY : src/components/camera_input.cpp.s

src/components/primitives_rendering_scene.o: src/components/primitives_rendering_scene.cpp.o
.PHONY : src/components/primitives_rendering_scene.o

# target to build an object file
src/components/primitives_rendering_scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/primitives_rendering_scene.cpp.o
.PHONY : src/components/primitives_rendering_scene.cpp.o

src/components/primitives_rendering_scene.i: src/components/primitives_rendering_scene.cpp.i
.PHONY : src/components/primitives_rendering_scene.i

# target to preprocess a source file
src/components/primitives_rendering_scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/primitives_rendering_scene.cpp.i
.PHONY : src/components/primitives_rendering_scene.cpp.i

src/components/primitives_rendering_scene.s: src/components/primitives_rendering_scene.cpp.s
.PHONY : src/components/primitives_rendering_scene.s

# target to generate assembly for a file
src/components/primitives_rendering_scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/primitives_rendering_scene.cpp.s
.PHONY : src/components/primitives_rendering_scene.cpp.s

src/components/scene_input.o: src/components/scene_input.cpp.o
.PHONY : src/components/scene_input.o

# target to build an object file
src/components/scene_input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/scene_input.cpp.o
.PHONY : src/components/scene_input.cpp.o

src/components/scene_input.i: src/components/scene_input.cpp.i
.PHONY : src/components/scene_input.i

# target to preprocess a source file
src/components/scene_input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/scene_input.cpp.i
.PHONY : src/components/scene_input.cpp.i

src/components/scene_input.s: src/components/scene_input.cpp.s
.PHONY : src/components/scene_input.s

# target to generate assembly for a file
src/components/scene_input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/scene_input.cpp.s
.PHONY : src/components/scene_input.cpp.s

src/components/simple_scene.o: src/components/simple_scene.cpp.o
.PHONY : src/components/simple_scene.o

# target to build an object file
src/components/simple_scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/simple_scene.cpp.o
.PHONY : src/components/simple_scene.cpp.o

src/components/simple_scene.i: src/components/simple_scene.cpp.i
.PHONY : src/components/simple_scene.i

# target to preprocess a source file
src/components/simple_scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/simple_scene.cpp.i
.PHONY : src/components/simple_scene.cpp.i

src/components/simple_scene.s: src/components/simple_scene.cpp.s
.PHONY : src/components/simple_scene.s

# target to generate assembly for a file
src/components/simple_scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/simple_scene.cpp.s
.PHONY : src/components/simple_scene.cpp.s

src/components/software_rendering_scene.o: src/components/software_rendering_scene.cpp.o
.PHONY : src/components/software_rendering_scene.o

# target to build an object file
src/components/software_rendering_scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/software_rendering_scene.cpp.o
.PHONY : src/components/software_rendering_scene.cpp.o

src/components/software_rendering_scene.i: src/components/software_rendering_scene.cpp.i
.PHONY : src/components/software_rendering_scene.i

# target to preprocess a source file
src/components/software_rendering_scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/software_rendering_scene.cpp.i
.PHONY : src/components/software_rendering_scene.cpp.i

src/components/software_rendering_scene.s: src/components/software_rendering_scene.cpp.s
.PHONY : src/components/software_rendering_scene.s

# target to generate assembly for a file
src/components/software_rendering_scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/software_rendering_scene.cpp.s
.PHONY : src/components/software_rendering_scene.cpp.s

src/components/text_renderer.o: src/components/text_renderer.cpp.o
.PHONY : src/components/text_renderer.o

# target to build an object file
src/components/text_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/text_renderer.cpp.o
.PHONY : src/components/text_renderer.cpp.o

src/components/text_renderer.i: src/components/text_renderer.cpp.i
.PHONY : src/components/text_renderer.i

# target to preprocess a source file
src/components/text_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/text_renderer.cpp.i
.PHONY : src/components/text_renderer.cpp.i

src/components/text_renderer.s: src/components/text_renderer.cpp.s
.PHONY : src/components/text_renderer.s

# target to generate assembly for a file
src/components/text_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/text_renderer.cpp.s
.PHONY : src/components/text_renderer.cpp.s

src/core/engine.o: src/core/engine.cpp.o
.PHONY : src/core/engine.o

# target to build an object file
src/core/engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/engine.cpp.o
.PHONY : src/core/engine.cpp.o

src/core/engine.i: src/core/engine.cpp.i
.PHONY : src/core/engine.i

# target to preprocess a source file
src/core/engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/engine.cpp.i
.PHONY : src/core/engine.cpp.i

src/core/engine.s: src/core/engine.cpp.s
.PHONY : src/core/engine.s

# target to generate assembly for a file
src/core/engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/engine.cpp.s
.PHONY : src/core/engine.cpp.s

src/core/gpu/depth_image.o: src/core/gpu/depth_image.cpp.o
.PHONY : src/core/gpu/depth_image.o

# target to build an object file
src/core/gpu/depth_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/depth_image.cpp.o
.PHONY : src/core/gpu/depth_image.cpp.o

src/core/gpu/depth_image.i: src/core/gpu/depth_image.cpp.i
.PHONY : src/core/gpu/depth_image.i

# target to preprocess a source file
src/core/gpu/depth_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/depth_image.cpp.i
.PHONY : src/core/gpu/depth_image.cpp.i

src/core/gpu/depth_image.s: src/core/gpu/depth_image.cpp.s
.PHONY : src/core/gpu/depth_image.s

# target to generate assembly for a file
src/core/gpu/depth_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/depth_image.cpp.s
.PHONY : src/core/gpu/depth_image.cpp.s

src/core/gpu/frame_buffer.o: src/core/gpu/frame_buffer.cpp.o
.PHONY : src/core/gpu/frame_buffer.o

# target to build an object file
src/core/gpu/frame_buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/frame_buffer.cpp.o
.PHONY : src/core/gpu/frame_buffer.cpp.o

src/core/gpu/frame_buffer.i: src/core/gpu/frame_buffer.cpp.i
.PHONY : src/core/gpu/frame_buffer.i

# target to preprocess a source file
src/core/gpu/frame_buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/frame_buffer.cpp.i
.PHONY : src/core/gpu/frame_buffer.cpp.i

src/core/gpu/frame_buffer.s: src/core/gpu/frame_buffer.cpp.s
.PHONY : src/core/gpu/frame_buffer.s

# target to generate assembly for a file
src/core/gpu/frame_buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/frame_buffer.cpp.s
.PHONY : src/core/gpu/frame_buffer.cpp.s

src/core/gpu/gpu_buffers.o: src/core/gpu/gpu_buffers.cpp.o
.PHONY : src/core/gpu/gpu_buffers.o

# target to build an object file
src/core/gpu/gpu_buffers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/gpu_buffers.cpp.o
.PHONY : src/core/gpu/gpu_buffers.cpp.o

src/core/gpu/gpu_buffers.i: src/core/gpu/gpu_buffers.cpp.i
.PHONY : src/core/gpu/gpu_buffers.i

# target to preprocess a source file
src/core/gpu/gpu_buffers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/gpu_buffers.cpp.i
.PHONY : src/core/gpu/gpu_buffers.cpp.i

src/core/gpu/gpu_buffers.s: src/core/gpu/gpu_buffers.cpp.s
.PHONY : src/core/gpu/gpu_buffers.s

# target to generate assembly for a file
src/core/gpu/gpu_buffers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/gpu_buffers.cpp.s
.PHONY : src/core/gpu/gpu_buffers.cpp.s

src/core/gpu/image.o: src/core/gpu/image.cpp.o
.PHONY : src/core/gpu/image.o

# target to build an object file
src/core/gpu/image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/image.cpp.o
.PHONY : src/core/gpu/image.cpp.o

src/core/gpu/image.i: src/core/gpu/image.cpp.i
.PHONY : src/core/gpu/image.i

# target to preprocess a source file
src/core/gpu/image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/image.cpp.i
.PHONY : src/core/gpu/image.cpp.i

src/core/gpu/image.s: src/core/gpu/image.cpp.s
.PHONY : src/core/gpu/image.s

# target to generate assembly for a file
src/core/gpu/image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/image.cpp.s
.PHONY : src/core/gpu/image.cpp.s

src/core/gpu/mesh.o: src/core/gpu/mesh.cpp.o
.PHONY : src/core/gpu/mesh.o

# target to build an object file
src/core/gpu/mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/mesh.cpp.o
.PHONY : src/core/gpu/mesh.cpp.o

src/core/gpu/mesh.i: src/core/gpu/mesh.cpp.i
.PHONY : src/core/gpu/mesh.i

# target to preprocess a source file
src/core/gpu/mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/mesh.cpp.i
.PHONY : src/core/gpu/mesh.cpp.i

src/core/gpu/mesh.s: src/core/gpu/mesh.cpp.s
.PHONY : src/core/gpu/mesh.s

# target to generate assembly for a file
src/core/gpu/mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/mesh.cpp.s
.PHONY : src/core/gpu/mesh.cpp.s

src/core/gpu/shader.o: src/core/gpu/shader.cpp.o
.PHONY : src/core/gpu/shader.o

# target to build an object file
src/core/gpu/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/shader.cpp.o
.PHONY : src/core/gpu/shader.cpp.o

src/core/gpu/shader.i: src/core/gpu/shader.cpp.i
.PHONY : src/core/gpu/shader.i

# target to preprocess a source file
src/core/gpu/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/shader.cpp.i
.PHONY : src/core/gpu/shader.cpp.i

src/core/gpu/shader.s: src/core/gpu/shader.cpp.s
.PHONY : src/core/gpu/shader.s

# target to generate assembly for a file
src/core/gpu/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/shader.cpp.s
.PHONY : src/core/gpu/shader.cpp.s

src/core/gpu/texture2D.o: src/core/gpu/texture2D.cpp.o
.PHONY : src/core/gpu/texture2D.o

# target to build an object file
src/core/gpu/texture2D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/texture2D.cpp.o
.PHONY : src/core/gpu/texture2D.cpp.o

src/core/gpu/texture2D.i: src/core/gpu/texture2D.cpp.i
.PHONY : src/core/gpu/texture2D.i

# target to preprocess a source file
src/core/gpu/texture2D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/texture2D.cpp.i
.PHONY : src/core/gpu/texture2D.cpp.i

src/core/gpu/texture2D.s: src/core/gpu/texture2D.cpp.s
.PHONY : src/core/gpu/texture2D.s

# target to generate assembly for a file
src/core/gpu/texture2D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/texture2D.cpp.s
.PHONY : src/core/gpu/texture2D.cpp.s

src/core/managers/texture_manager.o: src/core/managers/texture_manager.cpp.o
.PHONY : src/core/managers/texture_manager.o

# target to build an object file
src/core/managers/texture_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/managers/texture_manager.cpp.o
.PHONY : src/core/managers/texture_manager.cpp.o

src/core/managers/texture_manager.i: src/core/managers/texture_manager.cpp.i
.PHONY : src/core/managers/texture_manager.i

# target to preprocess a source file
src/core/managers/texture_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/managers/texture_manager.cpp.i
.PHONY : src/core/managers/texture_manager.cpp.i

src/core/managers/texture_manager.s: src/core/managers/texture_manager.cpp.s
.PHONY : src/core/managers/texture_manager.s

# target to generate assembly for a file
src/core/managers/texture_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/managers/texture_manager.cpp.s
.PHONY : src/core/managers/texture_manager.cpp.s

src/core/window/input_controller.o: src/core/window/input_controller.cpp.o
.PHONY : src/core/window/input_controller.o

# target to build an object file
src/core/window/input_controller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/window/input_controller.cpp.o
.PHONY : src/core/window/input_controller.cpp.o

src/core/window/input_controller.i: src/core/window/input_controller.cpp.i
.PHONY : src/core/window/input_controller.i

# target to preprocess a source file
src/core/window/input_controller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/window/input_controller.cpp.i
.PHONY : src/core/window/input_controller.cpp.i

src/core/window/input_controller.s: src/core/window/input_controller.cpp.s
.PHONY : src/core/window/input_controller.s

# target to generate assembly for a file
src/core/window/input_controller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/window/input_controller.cpp.s
.PHONY : src/core/window/input_controller.cpp.s

src/core/window/window_callbacks.o: src/core/window/window_callbacks.cpp.o
.PHONY : src/core/window/window_callbacks.o

# target to build an object file
src/core/window/window_callbacks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/window/window_callbacks.cpp.o
.PHONY : src/core/window/window_callbacks.cpp.o

src/core/window/window_callbacks.i: src/core/window/window_callbacks.cpp.i
.PHONY : src/core/window/window_callbacks.i

# target to preprocess a source file
src/core/window/window_callbacks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/window/window_callbacks.cpp.i
.PHONY : src/core/window/window_callbacks.cpp.i

src/core/window/window_callbacks.s: src/core/window/window_callbacks.cpp.s
.PHONY : src/core/window/window_callbacks.s

# target to generate assembly for a file
src/core/window/window_callbacks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/window/window_callbacks.cpp.s
.PHONY : src/core/window/window_callbacks.cpp.s

src/core/window/window_object.o: src/core/window/window_object.cpp.o
.PHONY : src/core/window/window_object.o

# target to build an object file
src/core/window/window_object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/window/window_object.cpp.o
.PHONY : src/core/window/window_object.cpp.o

src/core/window/window_object.i: src/core/window/window_object.cpp.i
.PHONY : src/core/window/window_object.i

# target to preprocess a source file
src/core/window/window_object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/window/window_object.cpp.i
.PHONY : src/core/window/window_object.cpp.i

src/core/window/window_object.s: src/core/window/window_object.cpp.s
.PHONY : src/core/window/window_object.s

# target to generate assembly for a file
src/core/window/window_object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/window/window_object.cpp.s
.PHONY : src/core/window/window_object.cpp.s

src/core/world.o: src/core/world.cpp.o
.PHONY : src/core/world.o

# target to build an object file
src/core/world.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/world.cpp.o
.PHONY : src/core/world.cpp.o

src/core/world.i: src/core/world.cpp.i
.PHONY : src/core/world.i

# target to preprocess a source file
src/core/world.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/world.cpp.i
.PHONY : src/core/world.cpp.i

src/core/world.s: src/core/world.cpp.s
.PHONY : src/core/world.s

# target to generate assembly for a file
src/core/world.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/world.cpp.s
.PHONY : src/core/world.cpp.s

src/lab/lab01/lab01.o: src/lab/lab01/lab01.cpp.o
.PHONY : src/lab/lab01/lab01.o

# target to build an object file
src/lab/lab01/lab01.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab01/lab01.cpp.o
.PHONY : src/lab/lab01/lab01.cpp.o

src/lab/lab01/lab01.i: src/lab/lab01/lab01.cpp.i
.PHONY : src/lab/lab01/lab01.i

# target to preprocess a source file
src/lab/lab01/lab01.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab01/lab01.cpp.i
.PHONY : src/lab/lab01/lab01.cpp.i

src/lab/lab01/lab01.s: src/lab/lab01/lab01.cpp.s
.PHONY : src/lab/lab01/lab01.s

# target to generate assembly for a file
src/lab/lab01/lab01.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab01/lab01.cpp.s
.PHONY : src/lab/lab01/lab01.cpp.s

src/lab/lab02/lab02.o: src/lab/lab02/lab02.cpp.o
.PHONY : src/lab/lab02/lab02.o

# target to build an object file
src/lab/lab02/lab02.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab02/lab02.cpp.o
.PHONY : src/lab/lab02/lab02.cpp.o

src/lab/lab02/lab02.i: src/lab/lab02/lab02.cpp.i
.PHONY : src/lab/lab02/lab02.i

# target to preprocess a source file
src/lab/lab02/lab02.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab02/lab02.cpp.i
.PHONY : src/lab/lab02/lab02.cpp.i

src/lab/lab02/lab02.s: src/lab/lab02/lab02.cpp.s
.PHONY : src/lab/lab02/lab02.s

# target to generate assembly for a file
src/lab/lab02/lab02.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab02/lab02.cpp.s
.PHONY : src/lab/lab02/lab02.cpp.s

src/lab/lab02/triangle_rasterizer.o: src/lab/lab02/triangle_rasterizer.cpp.o
.PHONY : src/lab/lab02/triangle_rasterizer.o

# target to build an object file
src/lab/lab02/triangle_rasterizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab02/triangle_rasterizer.cpp.o
.PHONY : src/lab/lab02/triangle_rasterizer.cpp.o

src/lab/lab02/triangle_rasterizer.i: src/lab/lab02/triangle_rasterizer.cpp.i
.PHONY : src/lab/lab02/triangle_rasterizer.i

# target to preprocess a source file
src/lab/lab02/triangle_rasterizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab02/triangle_rasterizer.cpp.i
.PHONY : src/lab/lab02/triangle_rasterizer.cpp.i

src/lab/lab02/triangle_rasterizer.s: src/lab/lab02/triangle_rasterizer.cpp.s
.PHONY : src/lab/lab02/triangle_rasterizer.s

# target to generate assembly for a file
src/lab/lab02/triangle_rasterizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab02/triangle_rasterizer.cpp.s
.PHONY : src/lab/lab02/triangle_rasterizer.cpp.s

src/lab/lab03/lab03.o: src/lab/lab03/lab03.cpp.o
.PHONY : src/lab/lab03/lab03.o

# target to build an object file
src/lab/lab03/lab03.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab03/lab03.cpp.o
.PHONY : src/lab/lab03/lab03.cpp.o

src/lab/lab03/lab03.i: src/lab/lab03/lab03.cpp.i
.PHONY : src/lab/lab03/lab03.i

# target to preprocess a source file
src/lab/lab03/lab03.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab03/lab03.cpp.i
.PHONY : src/lab/lab03/lab03.cpp.i

src/lab/lab03/lab03.s: src/lab/lab03/lab03.cpp.s
.PHONY : src/lab/lab03/lab03.s

# target to generate assembly for a file
src/lab/lab03/lab03.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab03/lab03.cpp.s
.PHONY : src/lab/lab03/lab03.cpp.s

src/lab/lab04/lab04.o: src/lab/lab04/lab04.cpp.o
.PHONY : src/lab/lab04/lab04.o

# target to build an object file
src/lab/lab04/lab04.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab04/lab04.cpp.o
.PHONY : src/lab/lab04/lab04.cpp.o

src/lab/lab04/lab04.i: src/lab/lab04/lab04.cpp.i
.PHONY : src/lab/lab04/lab04.i

# target to preprocess a source file
src/lab/lab04/lab04.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab04/lab04.cpp.i
.PHONY : src/lab/lab04/lab04.cpp.i

src/lab/lab04/lab04.s: src/lab/lab04/lab04.cpp.s
.PHONY : src/lab/lab04/lab04.s

# target to generate assembly for a file
src/lab/lab04/lab04.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab04/lab04.cpp.s
.PHONY : src/lab/lab04/lab04.cpp.s

src/lab/lab05/lab05.o: src/lab/lab05/lab05.cpp.o
.PHONY : src/lab/lab05/lab05.o

# target to build an object file
src/lab/lab05/lab05.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab05/lab05.cpp.o
.PHONY : src/lab/lab05/lab05.cpp.o

src/lab/lab05/lab05.i: src/lab/lab05/lab05.cpp.i
.PHONY : src/lab/lab05/lab05.i

# target to preprocess a source file
src/lab/lab05/lab05.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab05/lab05.cpp.i
.PHONY : src/lab/lab05/lab05.cpp.i

src/lab/lab05/lab05.s: src/lab/lab05/lab05.cpp.s
.PHONY : src/lab/lab05/lab05.s

# target to generate assembly for a file
src/lab/lab05/lab05.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab05/lab05.cpp.s
.PHONY : src/lab/lab05/lab05.cpp.s

src/lab/lab06/lab06.o: src/lab/lab06/lab06.cpp.o
.PHONY : src/lab/lab06/lab06.o

# target to build an object file
src/lab/lab06/lab06.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab06/lab06.cpp.o
.PHONY : src/lab/lab06/lab06.cpp.o

src/lab/lab06/lab06.i: src/lab/lab06/lab06.cpp.i
.PHONY : src/lab/lab06/lab06.i

# target to preprocess a source file
src/lab/lab06/lab06.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab06/lab06.cpp.i
.PHONY : src/lab/lab06/lab06.cpp.i

src/lab/lab06/lab06.s: src/lab/lab06/lab06.cpp.s
.PHONY : src/lab/lab06/lab06.s

# target to generate assembly for a file
src/lab/lab06/lab06.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab06/lab06.cpp.s
.PHONY : src/lab/lab06/lab06.cpp.s

src/lab/lab07/lab07.o: src/lab/lab07/lab07.cpp.o
.PHONY : src/lab/lab07/lab07.o

# target to build an object file
src/lab/lab07/lab07.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab07/lab07.cpp.o
.PHONY : src/lab/lab07/lab07.cpp.o

src/lab/lab07/lab07.i: src/lab/lab07/lab07.cpp.i
.PHONY : src/lab/lab07/lab07.i

# target to preprocess a source file
src/lab/lab07/lab07.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab07/lab07.cpp.i
.PHONY : src/lab/lab07/lab07.cpp.i

src/lab/lab07/lab07.s: src/lab/lab07/lab07.cpp.s
.PHONY : src/lab/lab07/lab07.s

# target to generate assembly for a file
src/lab/lab07/lab07.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab07/lab07.cpp.s
.PHONY : src/lab/lab07/lab07.cpp.s

src/lab/lab08/lab08.o: src/lab/lab08/lab08.cpp.o
.PHONY : src/lab/lab08/lab08.o

# target to build an object file
src/lab/lab08/lab08.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab08/lab08.cpp.o
.PHONY : src/lab/lab08/lab08.cpp.o

src/lab/lab08/lab08.i: src/lab/lab08/lab08.cpp.i
.PHONY : src/lab/lab08/lab08.i

# target to preprocess a source file
src/lab/lab08/lab08.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab08/lab08.cpp.i
.PHONY : src/lab/lab08/lab08.cpp.i

src/lab/lab08/lab08.s: src/lab/lab08/lab08.cpp.s
.PHONY : src/lab/lab08/lab08.s

# target to generate assembly for a file
src/lab/lab08/lab08.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab08/lab08.cpp.s
.PHONY : src/lab/lab08/lab08.cpp.s

src/lab/lab09/lab09.o: src/lab/lab09/lab09.cpp.o
.PHONY : src/lab/lab09/lab09.o

# target to build an object file
src/lab/lab09/lab09.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab09/lab09.cpp.o
.PHONY : src/lab/lab09/lab09.cpp.o

src/lab/lab09/lab09.i: src/lab/lab09/lab09.cpp.i
.PHONY : src/lab/lab09/lab09.i

# target to preprocess a source file
src/lab/lab09/lab09.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab09/lab09.cpp.i
.PHONY : src/lab/lab09/lab09.cpp.i

src/lab/lab09/lab09.s: src/lab/lab09/lab09.cpp.s
.PHONY : src/lab/lab09/lab09.s

# target to generate assembly for a file
src/lab/lab09/lab09.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab09/lab09.cpp.s
.PHONY : src/lab/lab09/lab09.cpp.s

src/lab/lab10/lab10.o: src/lab/lab10/lab10.cpp.o
.PHONY : src/lab/lab10/lab10.o

# target to build an object file
src/lab/lab10/lab10.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab10/lab10.cpp.o
.PHONY : src/lab/lab10/lab10.cpp.o

src/lab/lab10/lab10.i: src/lab/lab10/lab10.cpp.i
.PHONY : src/lab/lab10/lab10.i

# target to preprocess a source file
src/lab/lab10/lab10.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab10/lab10.cpp.i
.PHONY : src/lab/lab10/lab10.cpp.i

src/lab/lab10/lab10.s: src/lab/lab10/lab10.cpp.s
.PHONY : src/lab/lab10/lab10.s

# target to generate assembly for a file
src/lab/lab10/lab10.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab10/lab10.cpp.s
.PHONY : src/lab/lab10/lab10.cpp.s

src/lab/lab11/lab11.o: src/lab/lab11/lab11.cpp.o
.PHONY : src/lab/lab11/lab11.o

# target to build an object file
src/lab/lab11/lab11.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab11/lab11.cpp.o
.PHONY : src/lab/lab11/lab11.cpp.o

src/lab/lab11/lab11.i: src/lab/lab11/lab11.cpp.i
.PHONY : src/lab/lab11/lab11.i

# target to preprocess a source file
src/lab/lab11/lab11.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab11/lab11.cpp.i
.PHONY : src/lab/lab11/lab11.cpp.i

src/lab/lab11/lab11.s: src/lab/lab11/lab11.cpp.s
.PHONY : src/lab/lab11/lab11.s

# target to generate assembly for a file
src/lab/lab11/lab11.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab/lab11/lab11.cpp.s
.PHONY : src/lab/lab11/lab11.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils/gl_utils.o: src/utils/gl_utils.cpp.o
.PHONY : src/utils/gl_utils.o

# target to build an object file
src/utils/gl_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/utils/gl_utils.cpp.o
.PHONY : src/utils/gl_utils.cpp.o

src/utils/gl_utils.i: src/utils/gl_utils.cpp.i
.PHONY : src/utils/gl_utils.i

# target to preprocess a source file
src/utils/gl_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/utils/gl_utils.cpp.i
.PHONY : src/utils/gl_utils.cpp.i

src/utils/gl_utils.s: src/utils/gl_utils.cpp.s
.PHONY : src/utils/gl_utils.s

# target to generate assembly for a file
src/utils/gl_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/utils/gl_utils.cpp.s
.PHONY : src/utils/gl_utils.cpp.s

src/utils/text_utils.o: src/utils/text_utils.cpp.o
.PHONY : src/utils/text_utils.o

# target to build an object file
src/utils/text_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/utils/text_utils.cpp.o
.PHONY : src/utils/text_utils.cpp.o

src/utils/text_utils.i: src/utils/text_utils.cpp.i
.PHONY : src/utils/text_utils.i

# target to preprocess a source file
src/utils/text_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/utils/text_utils.cpp.i
.PHONY : src/utils/text_utils.cpp.i

src/utils/text_utils.s: src/utils/text_utils.cpp.s
.PHONY : src/utils/text_utils.s

# target to generate assembly for a file
src/utils/text_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/utils/text_utils.cpp.s
.PHONY : src/utils/text_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GFXFramework"
	@echo "... src/components/camera_input.o"
	@echo "... src/components/camera_input.i"
	@echo "... src/components/camera_input.s"
	@echo "... src/components/primitives_rendering_scene.o"
	@echo "... src/components/primitives_rendering_scene.i"
	@echo "... src/components/primitives_rendering_scene.s"
	@echo "... src/components/scene_input.o"
	@echo "... src/components/scene_input.i"
	@echo "... src/components/scene_input.s"
	@echo "... src/components/simple_scene.o"
	@echo "... src/components/simple_scene.i"
	@echo "... src/components/simple_scene.s"
	@echo "... src/components/software_rendering_scene.o"
	@echo "... src/components/software_rendering_scene.i"
	@echo "... src/components/software_rendering_scene.s"
	@echo "... src/components/text_renderer.o"
	@echo "... src/components/text_renderer.i"
	@echo "... src/components/text_renderer.s"
	@echo "... src/core/engine.o"
	@echo "... src/core/engine.i"
	@echo "... src/core/engine.s"
	@echo "... src/core/gpu/depth_image.o"
	@echo "... src/core/gpu/depth_image.i"
	@echo "... src/core/gpu/depth_image.s"
	@echo "... src/core/gpu/frame_buffer.o"
	@echo "... src/core/gpu/frame_buffer.i"
	@echo "... src/core/gpu/frame_buffer.s"
	@echo "... src/core/gpu/gpu_buffers.o"
	@echo "... src/core/gpu/gpu_buffers.i"
	@echo "... src/core/gpu/gpu_buffers.s"
	@echo "... src/core/gpu/image.o"
	@echo "... src/core/gpu/image.i"
	@echo "... src/core/gpu/image.s"
	@echo "... src/core/gpu/mesh.o"
	@echo "... src/core/gpu/mesh.i"
	@echo "... src/core/gpu/mesh.s"
	@echo "... src/core/gpu/shader.o"
	@echo "... src/core/gpu/shader.i"
	@echo "... src/core/gpu/shader.s"
	@echo "... src/core/gpu/texture2D.o"
	@echo "... src/core/gpu/texture2D.i"
	@echo "... src/core/gpu/texture2D.s"
	@echo "... src/core/managers/texture_manager.o"
	@echo "... src/core/managers/texture_manager.i"
	@echo "... src/core/managers/texture_manager.s"
	@echo "... src/core/window/input_controller.o"
	@echo "... src/core/window/input_controller.i"
	@echo "... src/core/window/input_controller.s"
	@echo "... src/core/window/window_callbacks.o"
	@echo "... src/core/window/window_callbacks.i"
	@echo "... src/core/window/window_callbacks.s"
	@echo "... src/core/window/window_object.o"
	@echo "... src/core/window/window_object.i"
	@echo "... src/core/window/window_object.s"
	@echo "... src/core/world.o"
	@echo "... src/core/world.i"
	@echo "... src/core/world.s"
	@echo "... src/lab/lab01/lab01.o"
	@echo "... src/lab/lab01/lab01.i"
	@echo "... src/lab/lab01/lab01.s"
	@echo "... src/lab/lab02/lab02.o"
	@echo "... src/lab/lab02/lab02.i"
	@echo "... src/lab/lab02/lab02.s"
	@echo "... src/lab/lab02/triangle_rasterizer.o"
	@echo "... src/lab/lab02/triangle_rasterizer.i"
	@echo "... src/lab/lab02/triangle_rasterizer.s"
	@echo "... src/lab/lab03/lab03.o"
	@echo "... src/lab/lab03/lab03.i"
	@echo "... src/lab/lab03/lab03.s"
	@echo "... src/lab/lab04/lab04.o"
	@echo "... src/lab/lab04/lab04.i"
	@echo "... src/lab/lab04/lab04.s"
	@echo "... src/lab/lab05/lab05.o"
	@echo "... src/lab/lab05/lab05.i"
	@echo "... src/lab/lab05/lab05.s"
	@echo "... src/lab/lab06/lab06.o"
	@echo "... src/lab/lab06/lab06.i"
	@echo "... src/lab/lab06/lab06.s"
	@echo "... src/lab/lab07/lab07.o"
	@echo "... src/lab/lab07/lab07.i"
	@echo "... src/lab/lab07/lab07.s"
	@echo "... src/lab/lab08/lab08.o"
	@echo "... src/lab/lab08/lab08.i"
	@echo "... src/lab/lab08/lab08.s"
	@echo "... src/lab/lab09/lab09.o"
	@echo "... src/lab/lab09/lab09.i"
	@echo "... src/lab/lab09/lab09.s"
	@echo "... src/lab/lab10/lab10.o"
	@echo "... src/lab/lab10/lab10.i"
	@echo "... src/lab/lab10/lab10.s"
	@echo "... src/lab/lab11/lab11.o"
	@echo "... src/lab/lab11/lab11.i"
	@echo "... src/lab/lab11/lab11.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils/gl_utils.o"
	@echo "... src/utils/gl_utils.i"
	@echo "... src/utils/gl_utils.s"
	@echo "... src/utils/text_utils.o"
	@echo "... src/utils/text_utils.i"
	@echo "... src/utils/text_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

